#!/bin/sh

set -e


# This variable is required otherwise
# /usr/share/live/build/scripts/build/binary_debian-installer fails because
# the version is empty (nothing known in
# /usr/share/live/build/functions/releases.sh)
# export RELEASE_star="0.60"

## install eatmydata early
#~ if [ ! -f chroot/usr/lib/x86_64-linux-gnu/libeatmydata.so ]; then
	#~ apt-get download libeatmydata1
	#~ sudo dpkg-deb --extract libeatmydata1*deb chroot
	#~ rm -f libeatmydata1*.deb
#~ fi

# export MKSQUASHFS_OPTIONS="-comp xz"

# export MKSQUASHFS_OPTIONS=" -no-recovery -always-use-fragments -b 1048576 -comp xz -Xbcj x86 -Xdict-size 75%"

# export MKSQUASHFS_OPTIONS=" -no-recovery -always-use-fragments -b 1048576 -comp xz -Xbcj x86"

#  jessie verion of squash-tools is 4.2!
export MKSQUASHFS_OPTIONS=" -no-recovery -always-use-fragments -b 1048576"

# eatmydata lb build noauto "${@}" 2>&1 | tee "Build - $(date "+%d.%m.%Y - %H:%M").log"
lb build noauto "${@}" 2>&1 | tee "Build - $(date "+%d.%m.%Y - %H:%M").log"
